trigger:
  branches:
    include:
      - main
      - feature/*
    - refs/pull/*/merge

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Construct the tag name using the current date and time
    tag=$(date +"%Y%m%d-%H%M%S")
    git tag $tag
    git push origin $tag
  displayName: 'Create Git tag'
  condition: |
        and(
          succeeded(),
          ne(variables['Build.Reason'], 'PullRequest'),
          or(
            eq(variables['Build.SourceBranchName'], 'main'),
            startsWith(variables['Build.SourceBranchName'], 'feature/')
          ),
          eq(variables['Build.SourceBranch'], variables['Build.SourceVersion']),
          eq(variables['Build.Reason'], 'IndividualCI')
        )
