trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- script: |
    git config user.email "you@example.com"
    git config user.name "Your Name"
    git merge --no-ff origin/develop
    git tag -a $(date +"%Y%m%d%H%M%S") -m "Merge from develop"
    git push origin master --tags
  displayName: 'Merge and tag changes'
