trigger:
  branches:
    include:
      - master
      - develop
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Construct the tag name using the current date and time
    tag=$(date +"%Y%m%d-%H%M%S")
    git tag $tag
    git push origin $tag
  displayName: 'Create Git tag'
  condition: |
    and(
      succeeded(),
      eq(variables['Build.Reason'], 'PullRequest'),
      eq(variables['Build.SourceBranch'], 'refs/heads/master')
    )
