trigger:
  branches:
    include:
      - main
      - feature/*
    - refs/pull/*/merge:
      types: [merged]
      condition: |
        and(
          succeeded(),
          eq(variables['System.PullRequest.IsDraft'], 'false'),
          contains(variables['System.PullRequest.SourceBranch'], 'feature/'),
          eq(variables['System.PullRequest.Approvals'], '1')
        )

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    # Construct the tag name using the current date and time
    tag=$(date +"%Y%m%d-%H%M%S")
    git tag $tag
    git push origin $tag
  displayName: 'Create Git tag'
